---
- name: INCLUDE {{ ansible_os_family }} OS VARIABLES
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: install_epel.yml
  when: redhat_enabled

- import_tasks: install_nginx.yml
  when: redhat_enabled

- import_tasks: copy_config.yml
